; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
build_cache_dir = D:\AdobeAECache\PIOCache

[env:esp32-c3-devkitc-02]
platform = espressif32
monitor_speed = 115200
upload_speed = 921600
board = esp32-c3-devkitc-02
framework = arduino

board_build.filesystem = littlefs
board_build.partitions = c3partition.csv
board_build.usb_mode = "device"
board_build.usb_class = "cdc"
board_build.f_cpu = 160000000L

check_libraries = no

monitor_filters = esp32_exception_decoder

lib_archive = no
lib_ldf_mode = chain+
build_src_filter =
    +<*>
    -<.pio/libdeps/*/lua/onelua.c>
    -<.pio/libdeps/*/lua/lua.c>
    -<.pio/libdeps/*/lua/luac.c>
    -<.pio/libdeps/*/lua/testes/>

build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D CONFIG_NEWLIB_NANO_FORMAT
	-D ESP32_USE_FAST_MEM
	-Wno-unused-variable
	-Wno-unused-function
	-Os
	-ffunction-sections
	-fdata-sections
	-fmerge-all-constants
	-fno-unwind-tables
	-fno-asynchronous-unwind-tables
	-Wl,--gc-sections
	-DLUA_32BITS
	-DLUA_USE_C89_NUMBERS
	-std=gnu++17

build_unflags = 
	-O0
	-O1
	-O2
	-O3
	-Og
	-std=gnu++11

lib_deps = 
	olikraus/U8g2@ 2.36.15
	shaggydog/OneButton@ 1.5.0
	dfrobot/DFRobot_VL53L0X@ 1.0.0
	plerup/EspSoftwareSerial@ 8.2.0
	sparkfun/SparkFun External EEPROM Arduino Library@ 3.2.12
	tzapu/WiFiManager@ 2.0.17
	bblanchon/ArduinoJson@ 7.4.2

lib_ignore = lua